import asyncio
import functools
import logging
import math
import re
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query, Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.config import settings
from app.services.tile_generator import _get_transparent_png
from app.services.tile_queue import tile_queue
from app.services.tile_service import (
    calculate_tile_count,
    delete_all_tiles,
    get_tile,
    invalidate_tile_cache,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/tiles", tags=["tiles"])

TIME_SLOT_PATTERN = re.compile(r"^[a-zA-Z0-9_]{1,30}$")


def validate_time_slot(time_slot: str) -> None:
    if not TIME_SLOT_PATTERN.match(time_slot):
        raise HTTPException(status_code=400, detail="Invalid time slot identifier")


def validate_coords(z: int, x: int, y: int) -> None:
    if z < 0 or z > 22:
        raise HTTPException(status_code=400, detail="Zoom level out of range")
    max_val = 2**z
    if x < 0 or x >= max_val or y < 0 or y >= max_val:
        raise HTTPException(status_code=400, detail="Tile coordinates out of range")


# Fallback response for tiles not yet generated.
# no-store ensures the browser will re-request the tile later,
# when it may have been generated by the background worker.
# Created lazily via lru_cache on first access.
@functools.lru_cache(maxsize=1)
def _get_transparent_response() -> Response:
    return Response(
        content=_get_transparent_png(),
        media_type="image/png",
        headers={"Cache-Control": "no-cache"},
    )


@router.get(
    "/{time_slot}/{z}/{x}/{y}.png",
    name="get_tile",
    responses={
        200: {"content": {"image/png": {}}},
    },
)
async def get_tile_png(
    time_slot: str,
    z: int,
    x: int,
    y: int,
    db: AsyncSession = Depends(get_db),
) -> Response:
    """
    Get a heatmap tile.

    Lookup order:
    1. File cache on disk
    2. PostGIS database
    3. Transparent PNG fallback (tile enqueued for background generation)

    Missing tiles are returned as transparent PNGs — the base map layer
    shows through, so there are no visual artifacts.
    """
    validate_time_slot(time_slot)
    validate_coords(z, x, y)

    cache_path = Path(settings.tile_cache_dir) / time_slot / str(z) / f"{x}/{y}.png"

    # --- Layer 1: file cache ---
    if cache_path.exists():
        return Response(
            content=cache_path.read_bytes(),
            media_type="image/png",
            headers={"Cache-Control": "public, max-age=86400"},
        )

    # --- Layer 2: database ---
    png_data = await get_tile(time_slot, z, x, y, session=db)

    if png_data is not None:
        # Write to file cache for next request
        try:
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            cache_path.write_bytes(png_data)
        except Exception:
            pass

        return Response(
            content=png_data,
            media_type="image/png",
            headers={"Cache-Control": "public, max-age=86400"},
        )

    # --- Layer 3: not found — transparent fallback + enqueue ---
    await tile_queue.enqueue(time_slot, z, x, y)
    return _get_transparent_response()


@router.post(
    "/generate/{time_slot}/{z}/{x}/{y}",
    name="generate_tile",
)
async def generate_tile(
    time_slot: str,
    z: int,
    x: int,
    y: int,
) -> dict:
    """Enqueue a tile for background generation."""
    validate_time_slot(time_slot)
    validate_coords(z, x, y)
    await tile_queue.enqueue(time_slot, z, x, y)
    status = await tile_queue.queue_size()
    return {
        "status": "enqueued",
        "time_slot": time_slot,
        "z": z,
        "x": x,
        "y": y,
        **status,
    }


@router.get(
    "/queue-status",
    name="queue_status",
)
async def get_queue_status() -> dict:
    """Return current tile generation queue status."""
    return await tile_queue.queue_size()


def _parse_bbox(bbox_str: str) -> tuple[float, float, float, float]:
    """Parse and validate a bbox string 'min_lon,min_lat,max_lon,max_lat'."""
    parts = bbox_str.split(",")
    if len(parts) != 4:
        raise HTTPException(
            status_code=400,
            detail="bbox must be 'min_lon,min_lat,max_lon,max_lat'",
        )
    try:
        min_lon, min_lat, max_lon, max_lat = (float(p) for p in parts)
    except ValueError:
        raise HTTPException(status_code=400, detail="bbox values must be numbers")

    if not (-180 <= min_lon <= 180 and -180 <= max_lon <= 180):
        raise HTTPException(status_code=400, detail="longitude must be in [-180, 180]")
    if not (-90 <= min_lat <= 90 and -90 <= max_lat <= 90):
        raise HTTPException(status_code=400, detail="latitude must be in [-90, 90]")
    if min_lon >= max_lon or min_lat >= max_lat:
        raise HTTPException(status_code=400, detail="min must be less than max")

    return min_lon, min_lat, max_lon, max_lat


def _tile_bounds(
    min_lon: float, min_lat: float, max_lon: float, max_lat: float, z: int
) -> tuple[int, int, int, int]:
    """Compute (x_min, x_max, y_min, y_max) tile indices for a bbox at zoom z."""
    n = 2 ** z
    tile_size_deg = 360.0 / n

    x_min = math.floor((min_lon + 180.0) / tile_size_deg)
    x_max = math.floor((max_lon + 180.0) / tile_size_deg)
    y_min = math.floor((90.0 - max_lat) / tile_size_deg)
    y_max = math.floor((90.0 - min_lat) / tile_size_deg)

    return (
        max(0, x_min),
        min(n - 1, x_max),
        max(0, y_min),
        min(n - 1, y_max),
    )


@router.post(
    "/admin/invalidate-all",
    name="invalidate_all_tiles",
)
async def invalidate_all_tiles(
    dry_run: bool = Query(False),
    bbox: str | None = Query(None),
    z_min: int | None = Query(None),
    z_max: int | None = Query(None),
) -> dict:
    """Invalidate all tiles and re-enqueue them for regeneration.

    Steps:
    1. Clear Redis queue (streams, dedup set, layer counters)
    2. Truncate tiles table in DB
    3. Delete file cache on disk
    4. Calculate all tile coordinates in the bbox for z_min..z_max
    5. Enqueue all tiles for pre-generation
    """
    # TODO: add admin auth check

    # Resolve bbox and zoom range
    bbox_str = bbox if bbox is not None else settings.pregen_bbox
    min_lon, min_lat, max_lon, max_lat = _parse_bbox(bbox_str)
    effective_z_min = z_min if z_min is not None else settings.pregen_z_min
    effective_z_max = z_max if z_max is not None else settings.pregen_z_max

    if effective_z_min < 0 or effective_z_max > 22 or effective_z_min > effective_z_max:
        raise HTTPException(
            status_code=400,
            detail="z_min and z_max must be in [0, 22] and z_min <= z_max",
        )

    # Calculate tile count
    total_tiles = await calculate_tile_count(
        (min_lon, min_lat, max_lon, max_lat), effective_z_min, effective_z_max
    )

    if dry_run:
        return {
            "status": "dry_run",
            "dry_run": True,
            "cache_dir": settings.tile_cache_dir,
            "total_tiles": total_tiles,
            "zoom_range": [effective_z_min, effective_z_max],
            "bbox": bbox_str,
        }

    # --- Step 1: Clear Redis queue ---
    await tile_queue.clear_all()

    # --- Step 2: Truncate DB ---
    deleted_db_rows = await delete_all_tiles()

    # --- Step 3: Delete file cache ---
    await invalidate_tile_cache(settings.tile_cache_dir)

    # --- Step 4 & 5: Enqueue all tiles ---
    queued = 0
    time_slot = "day"

    for z in range(effective_z_min, effective_z_max + 1):
        x_min, x_max, y_min, y_max = _tile_bounds(min_lon, min_lat, max_lon, max_lat, z)

        for x in range(x_min, x_max + 1):
            for y in range(y_min, y_max + 1):
                await tile_queue.enqueue(time_slot, z, x, y, priority="pregen")
                queued += 1

                if queued % 100 == 0:
                    await asyncio.sleep(0)

    logger.info(
        "Invalidated all tiles: deleted_db=%d, queued=%d, zoom=[%d,%d], bbox=%s",
        deleted_db_rows, queued, effective_z_min, effective_z_max, bbox_str,
    )

    return {
        "status": "invalidated_and_enqueued",
        "dry_run": False,
        "cache_dir": settings.tile_cache_dir,
        "deleted_db_rows": deleted_db_rows,
        "queued_tiles": queued,
        "zoom_range": [effective_z_min, effective_z_max],
        "bbox": bbox_str,
    }
